### PR TITLE
39-Add PUT methods for the JSON-first APIs

### LINKED ISSUE #39: Add PUT methods for the JSON-first APIs
Tagging @softchris for visibility

### PR DESCRIPTION
**Pull request by davidbuckleyni**
Hi @csharpfritz @softchris  Let me no if anything else needs done I added a enum value Put=24 We might need to change that number but saw you just doing multiples of 2 for the values.

Fixes #39

### CODE REVIEW

**Comment by verbedr** [comment]
The value of [Flags] enabled enum should be value in the list of 2 to the power of x where x is a positive natural number.  So in this case it should be 32. But then again the value of All should be the sum of all the above.

In general I tend to assign 1 << 0, 1 << 1, 1 << 2 and use int.MaxValue as the value for All.  (see https://stackoverflow.com/questions/3999922/why-use-the-bitwise-shift-operator-for-values-in-a-c-enum-definition, which is about the c language but is also valid here)

Anyway Update and Put are synonyms. Perhaps you should use the Update value of that enum

**Comment by davidbuckleyni** [comment]
> The value of [Flags] enabled enum should be a value of 2 to the power of x where x is a positive natural number. So in this case it should be 32. But then again the value of All should be the sum of all the above.
> 
> In general I tend to assign 1 << 0, 1 << 1, 1 << 2 and use int.MaxValue as the value for All. (see for example https://stackoverflow.com/questions/3999922/why-use-the-bitwise-shift-operator-for-values-in-a-c-enum-definition)
> 
> Anyway Update and Put are synonyms. Perhaps you should use the Update value of that enum

I was thinking that but what if the program wants to no their is a dif between the update and the put via the enum just thinking out loud here but could catch.

**Comment by csharpfritz** [comment]
Agreed with @verbedr - the PUT HTTP verb is the same as update and should reference the Update enum

**Comment by davidbuckleyni** [comment]
> Agreed with @verbedr - the PUT HTTP verb is the same as update and should reference the Update enum.
> 
> Let's consolidate on the ApisToGenerate.Update value and then we can accept this

Ok Wil do that this evening then then put it on thru.

**Comment by davidbuckleyni** [comment]
Sorry forgot to tag and say done @csharpfritz

**Comment by csharpfritz** [comment]
Thank you for that update!  This was a good addition

**Pull request merged**
