### PR TITLE
Remove 'Fritz' from the project, namespace, and NuGet package names

### PR DESCRIPTION
**Pull request by ScottKane**
That should be `Fritz.` removed from everywhere for #41

### CODE REVIEW

**Comment by ScottKane** [comment]
Sorry I missed that, will get it sorted tonight.

**Comment by ScottKane** [comment]
Fixed build.yaml and buildAndDeploy.yaml. Let me know if there's anything else I missed but I think that should be it.

**Comment by ScottKane** [comment]
Not sure why this build is failing, can't find any further references to `Fritz.` in the project. Any ideas?

**Comment by verbedr** [comment]
Hi @ScottKane,
The build action list all the references and using's to Fritz as an error. I cloned your repo and got the same result when performing "dotnet build" in the root of the repository.

I'm not sure how you are looking for the references to "Fritz.", but I would suggest by starting a solution wide search to "Fritz."

Some reference I found:

- https://github.com/ScottKane/InstantAPIs/blob/fd928ea83b3f1a7f7b5235e1ab68a34bc2ad35b2/Test/Test.csproj#L27
- https://github.com/ScottKane/InstantAPIs/blob/fd928ea83b3f1a7f7b5235e1ab68a34bc2ad35b2/WorkingApi/WorkingApi.csproj#L22
- https://github.com/ScottKane/InstantAPIs/blob/fd928ea83b3f1a7f7b5235e1ab68a34bc2ad35b2/Test/Configuration/WithOnlyIncludes.cs#L1
- https://github.com/ScottKane/InstantAPIs/blob/fd928ea83b3f1a7f7b5235e1ab68a34bc2ad35b2/Test/Configuration/WithoutIncludes.cs#L1
- https://github.com/ScottKane/InstantAPIs/blob/fd928ea83b3f1a7f7b5235e1ab68a34bc2ad35b2/InstantAPIs.Generators.Tests/DbContextAPIGeneratorTests.cs#L1
- ...

This is not the complete list, but just a small sample to help you find why you can't find them.  I hope this helps

Kr
Dries

**Comment by ScottKane** [comment]
Unsure what happened with the last commit, the changes were made but half of them had been stashed for some reason. Had to remove `using Mock;` from `TestJson/Program.cs` as that was causing the build to fail, not sure how that ever worked as the project has no Mock dependency? There was also a load of unused using directives but I thought it best to leave them for now. This is the only one I touched.

**Comment by verbedr** [comment]
Don't worry about it. It happens to me also, and this is one of the purpose of having the CI.  As a tip, when this happens to me, I tend to use rebase and reorganize the commits so nobody notices my mistake...

On another note, can you remove the .idea folder from the commits and put this folder in the .gitignore file? @csharpfritz I guess we will not standardize on that IDEA tool, and just like for visual code we do not include the cache/config folder ".vs/".

**Comment by ScottKane** [comment]
Done, I'm surprised `.idea` isn't already ignored in the gitignore template next to `.vs` at this point but should be fine going forward.

**Pull request merged**
